#!/bin/bash

readonly BASE_URL="http://localhost:8080"

echo "Creating Books...\n"
readonly BOOKS_URI="/books"

declare -a book_list=(
	'{
		"author": "Paula Hawkins",
		"title": "The Girl on the Train",
		"image": "http://wolox-training.s3.amazonaws.com/uploads/content.jpeg",
		"year": "2015",
		"genre": "suspense"
	}'
	'{
		"author": "Andy Weir",
		"title": "The Martian",
		"image": "http://wolox-training.s3.amazonaws.com/uploads/41DNuJfahyL._SX322_BO1_204_203_200_.jpg",
		"year": "2011",
		"genre": "fiction"
	}'
	'{
		"author": "Lois Duncan",
		"title": "Locked in time",
		"image": "http://wolox-training.s3.amazonaws.com/uploads/6942334-M.jpg",
		"year": "1985",
		"genre": "suspense"
	}'
	'{
		"author": "Kyle Simpson",
		"title": "You Don'"'"'t Know JS: Async & Performance",
		"image": "http://wolox-training.s3.amazonaws.com/uploads/cover.jpg",
		"year": "2014",
		"genre": "programming"
	}'
	'{
		"author": "Christopher Pike",
		"title": "Scavenger Hunt",
		"image": "http://wolox-training.s3.amazonaws.com/uploads/6963511-M.jpg",
		"year": "1989",
		"genre": "suspense"
	}'
	'{
		"author": "Anthony Doerr",
		"title": "All the Light We Cannot See",
		"image": "http://wolox-training.s3.amazonaws.com/uploads/content.jpeg",
		"year": "2014",
		"genre": "suspense"
	}'
	'{
		"author": "John Katzenbach",
		"title": "The analyst",
		"image": "http://wolox-training.s3.amazonaws.com/uploads/el-psicoanalista-analyst-john-katzenbach-paperback-cover-art.jpg",
		"year": "2003",
		"genre": "thriller"}'
	'{
		"author": "Dani",
		"title": "La Gran Dani",
		"image": "",
    "year": "1992",
		"genre": "fiction"
	}'
	'{
		"author": "Douglas Crockford",
		"title": "Javascript: The Good Parts",
		"image": "http://wolox-training.s3.amazonaws.com/uploads/js_good_parts.png",
		"year": "2008",
		"genre": "programming"
	}'
)

for book in "${book_list[@]}"
do
	curl \
	-d "$book" \
	-H "Content-Type: application/json" \
	-X POST \
	"$BASE_URL$BOOKS_URI"

	echo "\n"
done

echo "Done!\n\n"


echo "Creating Users...\n"
readonly USERS_URI="/users"

declare -a user_list=(
	'{
		"username": "admin",
		"password": "admin"
	}'
	'{
		"username": "juanrodriguez",
		"password": "juanrodriguez"
	}'
	'{
		"username": "manuelhernandez",
		"password": "manuelhernandez"
	}'
	'{
		"username": "rodrigogarcia",
		"password": "rodrigogarcia"
	}'
	'{
		"username": "sergiohernandez",
		"password": "sergiohernandez"
	}'
	'{
		"username": "test",
		"password": "test"
	}'
)

for user in "${user_list[@]}"
do
	curl \
	-d "$user" \
	-H "Content-Type: application/json" \
	-X POST \
	"$BASE_URL$USERS_URI"

	echo "\n"
done

echo "Done!\n\n"


echo "Creating Comments...\n"
readonly COMMENT_EXAMPLE="I recommend this book! It's really interesting."

for book_id in {1..5}
do
	for user_id in {1..3}
	do
		curl \
		-d  '{"content": '"\"$COMMENT_EXAMPLE\""', "userID": '$user_id', "bookID": '$book_id' }' \
		-H "Content-Type: application/json" \
		-X POST \
		"$BASE_URL/books/$book_id/comments"

		echo "\n"
	done
done

echo "Done!\n\n"


echo "Creating Rents...\n"

readonly RENT_USER=1
readonly RENTS_URL="/users/$RENT_USER/rents"

for book_id in {1..2}
do
	curl \
	-d  '{"userID": '$RENT_USER', "bookID": '$book_id', "from": "2018-09-17", "to": "2018-09-24"}' \
	-H "Content-Type: application/json" \
	-X POST \
	"$BASE_URL$RENTS_URL"

	echo "\n"
done

echo "Done!\n\n"


echo "Creating Wishes...\n"

readonly WISH_USER=1
readonly WISHES_URL="/users/$WISH_USER/wishes"

for book_id in {3..4}
do
	curl \
	-d  '{"userID": '$WISH_USER', "bookID": '$book_id'}' \
	-H "Content-Type: application/json" \
	-X POST \
	"$BASE_URL$WISHES_URL"

	echo "\n"
done

echo "Done!\n\n"
